name: Test NuGet Login

on:
  workflow_dispatch:

jobs:
  login-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: NuGet login
        id: nuget_login
        uses: your-org/nuget-login@main
        with:
          user: ${{ secrets.NUGET_USER }}
          source: https://api.nuget.org/v3/index.json

      - name: Output API key
        run: echo "Key is ${{ steps.nuget_login.outputs.NUGET_API_KEY }}"
