name: Test NuGet Login Step 2

on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  test-token-exchange:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: NuGet login (exchange OIDC token for API key)
        id: nuget_login
        uses: your-org/nuget-login@v1
        with:
          user: ${{ secrets.NUGET_USER }}
          source: https://api.nuget.org/v3/index.json
          token-service-url: https://your-nuget-server/api/v2/token

      - name: Show API key length (masked)
        run: echo "API key length is ${{ steps.nuget_login.outputs.NUGET_API_KEY && steps.nuget_login.outputs.NUGET_API_KEY.length }}"
